# Generated by Django 2.0.6 on 2018-06-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convo20', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medal',
            name='branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medal',
            name='programme',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='programme',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
