# Generated by Django 2.0.5 on 2018-06-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convo20', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'VIP',
                'verbose_name_plural': 'VIPs',
            },
        ),
    ]
