# Generated by Django 2.0.5 on 2018-06-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convo20', '0002_vip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField(unique=True)),
                ('rollno', models.IntegerField(unique=True)),
                ('medal', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('programme', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Medal Winner',
                'verbose_name_plural': 'Medal Winners',
            },
        ),
    ]
